description: Restores and saves the cocoa pods cache.
steps:
  - restore_cache:
      name: Restore CocoaPods Cache
      keys:
        - 3-pods-{{ arch }}-{{ checksum "ios/Podfile.lock" }}
        - 3-pods-{{ arch }}-
  - run:
      name: '[CP] Install CocoaPods'
      command: bundle exec pod install
      working_directory: ios
  - save_cache:
      name: Save CocoaPods Cache
      key: 3-pods-{{ arch }}-{{ checksum "ios/Podfile.lock" }}
      paths:
        - ~/Library/Caches/CocoaPods/
