when: << pipeline.parameters.run_commit >>
jobs:
  - check
  - bump_version:
      delivery: none
  - build_android:
      requires:
        - check
        - bump_version
  - build_ios:
      requires:
        - check
        - bump_version
  - deliver_browser_stack:
      requires:
        - build_android
        - build_ios
