docker:
  - image: circleci/android:api-29-node
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
shell: /bin/bash -eo pipefail
steps:
  - checkout
  - prepare_workspace
  - restore_ruby_cache:
      directory: android
  - run:
      name: 'BrowserStack Upload android'
      command: bundle exec fastlane android upload_to_browserstack
      working_directory: android
  - restore_ruby_cache:
      directory: ios
  - run:
      name: 'BrowserStack Upload iOS'
      command: bundle exec fastlane ios upload_to_browserstack
      working_directory: ios
